### ISSUE TITLE
 Invalid VNode type: Symbol(Comment) (symbol) 

### ISSUE THREAD

**Issue by amrzteb** [cuteCloud/vue-qqmap#6]
<h3>vue新手 引入组件遇到点问题，有空就帮看下</h3>

- 依赖是通过yarn add  vue-qqmap 安装的

- 引入的效果如下：
![image](https://user-images.githubusercontent.com/31942129/145430534-6af50323-dfe8-4c59-852f-a8d1f4a6a9f3.png)

- console输出如下：
![image](https://user-images.githubusercontent.com/31942129/145430833-54a7515a-1ac8-4d12-afcf-d92d490ed577.png)

- 代码
![image](https://user-images.githubusercontent.com/31942129/145431370-9e68313b-feff-4852-abb7-413653dc6964.png)

```
<vqqmap
        v-model="qqmap_location"
        :options="options"
        @update="mapChange"
      />
```

**Comment by cuteCloud** [comment]
修改你的vue版本为3.2.26及一下，目前已知3.2.3版本的vue有问题

**Comment by cuteCloud** [comment]
> ### vue新手 引入组件遇到点问题，有空就帮看下
> * 依赖是通过yarn add  vue-qqmap 安装的
> * 引入的效果如下：
>   ![image](https://user-images.githubusercontent.com/31942129/145430534-6af50323-dfe8-4c59-852f-a8d1f4a6a9f3.png)
> * console输出如下：
>   ![image](https://user-images.githubusercontent.com/31942129/145430833-54a7515a-1ac8-4d12-afcf-d92d490ed577.png)
> * 代码
>   ![image](https://user-images.githubusercontent.com/31942129/145431370-9e68313b-feff-4852-abb7-413653dc6964.png)
> 
> ```
> <vqqmap
>         v-model="qqmap_location"
>         :options="options"
>         @update="mapChange"
>       />
> ```
修改你的vue版本为3.2.26及一下，目前已知3.2.3版本的vue有问题

**Comment by cuteCloud** [comment]
> ### vue新手 引入组件遇到点问题，有空就帮看下
> * 依赖是通过yarn add  vue-qqmap 安装的
> * 引入的效果如下：
>   ![image](https://user-images.githubusercontent.com/31942129/145430534-6af50323-dfe8-4c59-852f-a8d1f4a6a9f3.png)
> * console输出如下：
>   ![image](https://user-images.githubusercontent.com/31942129/145430833-54a7515a-1ac8-4d12-afcf-d92d490ed577.png)
> * 代码
>   ![image](https://user-images.githubusercontent.com/31942129/145431370-9e68313b-feff-4852-abb7-413653dc6964.png)
> 
> ```
> <vqqmap
>         v-model="qqmap_location"
>         :options="options"
>         @update="mapChange"
>       />
> ```

最新修正，因为vue3.2.0+引入了setup带来的问题，已经修复，无需降级vue，升级vue-qqmap到1.1.1版本即可

**Comment by amrzteb** [comment]
OK
